### ISSUE TITLE
API Key Exposed

### ISSUE THREAD

**Issue by vanheaven-ui** [DoviMaj/weather-app#1]
Great job on this. However, the API key seems exposed. You might want to use Dotenv  to manage environment variables,

**Comment by DoviMaj** [comment]
Thank u very much 🥰. Thx for the concern also, but since there is no credit card attached to it I don't care lol. Also I couldn't use dot env on a font-end only app. 

On a not connected side note do u know microverse uses The Odin Project's content without permission... And ppl are paying for free content? And that's illegal..

**Comment by vanheaven-ui** [comment]
Hahaha, The Odin Project content is free to use. What permission is needed except acknowledging when you use it. Maybe they have some sort of contract going on under the hood.

**Comment by DoviMaj** [comment]
We have no positive relationship with MV. TOP did not give any sort of permissions to use our content.
